sudo: required
services:
  - docker

before_install:
  - docker build -t ntayz/react-with-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true ntayz/react-with-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'runner'
  env: 'Runner-env'
  bucket_name: 'elasticbeanstalk-us-east-2-412260836763'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
